"""Commerce domain public surface (contracts 層の正規配置)."""

from contracts.protocol.commerce.interfaces import (
    FlowContext,
    FlowStatus,
    FlowStepType,
    ICart,
    ICommerceAI,
    ICommerceFlow,
    ICommerceStep,
    IDealRecommender,
    IIntentAnalyzer,
    IOffer,
    IOfferProvider,
    IPayment,
    IProduct,
    ITransaction,
)
from contracts.protocol.commerce.models import (
    Cart,
    CartItem,
    DirectOffer,
    IntentConfidence,
    IntentType,
    Offer,
    OfferType,
    PaymentMethod,
    Product,
    ProductCategory,
    PurchaseIntent,
    Transaction,
    TransactionStatus,
)


__all__ = [
    # interfaces
    "FlowContext",
    "FlowStatus",
    "FlowStepType",
    "ICart",
    "ICommerceAI",
    "ICommerceFlow",
    "ICommerceStep",
    "IDealRecommender",
    "IIntentAnalyzer",
    "IOffer",
    "IOfferProvider",
    "IPayment",
    "IProduct",
    "ITransaction",
    # models
    "Cart",
    "CartItem",
    "DirectOffer",
    "IntentConfidence",
    "IntentType",
    "Offer",
    "OfferType",
    "PaymentMethod",
    "Product",
    "ProductCategory",
    "PurchaseIntent",
    "Transaction",
    "TransactionStatus",
]
