version: '3.8'
services:
  rag-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./documents:/app/documents
      - ./config:/app/config

  rag-client:
    build: .
    depends_on:
      - rag-server
    environment:
      - MCP_SERVER_URL=http://rag-server:8000
    command: python mcp_rag_client.py
