"""Compliance Reporter Agent - 合規 & 統計報告生成."""

from __future__ import annotations

from typing import Any

from agentflow import agent


@agent
class ComplianceReporterAgent:
    """報告生成 Agent.

    全工程の成果物を集約し、人間が読めるプロフェッショナルな報告書 (Markdown) を作成する。
    """

    def process(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """報告書を生成."""
        task_id = input_data.get("task_id", "unknown")
        analysis = input_data.get("analysis", {})
        design = input_data.get("design", {})
        transformation = input_data.get("transformation", {})
        quality = input_data.get("quality", {})
        fix = input_data.get("fix", {})

        report_lines = [
            f"# Modernization Compliance Report: {task_id}",
            "",
            "## 1. Executive Summary",
            f"- **Status**: {'SUCCESS' if quality.get('decision') in ['passed', 'known_legacy'] else 'FAILED'}",
            f"- **Migration Type**: {input_data.get('migration_type', 'COBOL to Java')}",
            f"- **Primary Module**: {analysis.get('meta', {}).get('module', 'Unknown')}",
            "",
            "## 2. Legacy Analysis Insights",
            f"- **Program ID**: {analysis.get('program_id', 'N/A')}",
            f"- **Loc (Legacy)**: {len(input_data.get('source_code', '').splitlines())} lines",
            f"- **Detected entry points**: {', '.join(analysis.get('entry_points', []))}",
            "",
            "## 3. Migration Design",
            f"- **Target Class**: {design.get('class_mapping', {}).get('primary_class', 'N/A')}",
            f"- **Applied Rules**: {len(design.get('mapping_rules', []))} rules registered",
            "",
            "## 4. Quality & Verification",
            f"- **Equivalence Check**: {'PASSED' if quality.get('decision') == 'passed' else 'CONDITIONAL'}",
            f"- **Severity**: {quality.get('severity', 'LOW')}",
            f"- **Reasoning**: {quality.get('reason', 'N/A')}",
            "",
            "## 5. Artifacts",
            "- **Target Code Generated**: Yes",
            f"- **Fixes Applied**: {'Yes' if fix.get('applied') else 'No'}",
            "",
            "---",
            "*Generated by Legacy-to-Agent™ Compliance Reporter.*",
        ]

        report_content = "\n".join(report_lines)

        return {"report_markdown": report_content, "success": True}
