services:
  llm-vllm:
    image: vllm/vllm-openai:v0.8.5
    container_name: llm-vllm
    ports:
      - 18001:8000
    restart: unless-stopped
    gpus: all
    ipc: host
    environment:
      HF_HOME: /root/.cache/huggingface
      CUDA_VISIBLE_DEVICES: "0"
    volumes:
      - /home/liush/.cache/huggingface:/root/.cache/huggingface
    command:
      - --model
      - Qwen/Qwen2.5-0.5B-Instruct
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --tensor-parallel-size
      - "1"
