services:
  llm-tgi:
    image: ghcr.io/huggingface/text-generation-inference:3.3.7
    container_name: llm-tgi
    ports:
    - 18003:80
    restart: unless-stopped
    gpus: all
    shm_size: 1g
    environment:
      HF_HOME: /data
      CUDA_VISIBLE_DEVICES: '0'
    volumes:
    - /home/liush/.cache/huggingface:/data
    command:
    - --model-id
    - Qwen/Qwen2.5-0.5B-Instruct
    - --port
    - '80'
