"""BackendBuilder - バックエンドコードビルダー.

FastAPI ベースのバックエンドコードを生成します。
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from agentflow.codegen.builders.base import BaseBuilder


if TYPE_CHECKING:
    from agentflow.core.interfaces import CodeGenOptions, WorkflowDefinition


class BackendBuilder(BaseBuilder):
    """バックエンドコードビルダー.

    FastAPI アプリケーションを生成します。
    """

    async def build(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> dict[str, str]:
        """バックエンドコードをビルド."""
        files: dict[str, str] = {}

        # メインアプリケーション
        files["app.py"] = self._generate_app(workflow, options)

        # ワークフロー定義
        files["workflow.py"] = self._generate_workflow(workflow, options)

        # 設定
        files["config.py"] = self._generate_config(options)

        # requirements.txt
        files["requirements.txt"] = self._generate_requirements()

        # Dockerfile
        if options.include_docker:
            files["Dockerfile"] = self._generate_dockerfile(options)
            files["docker-compose.yml"] = self._generate_docker_compose(options)

        # README
        if options.include_readme:
            files["README.md"] = self._generate_readme(workflow, options)

        # テスト
        if options.include_tests:
            files["tests/__init__.py"] = ""
            files["tests/test_app.py"] = self._generate_tests(workflow, options)

        # 環境変数テンプレート
        files[".env.example"] = self._generate_env_example()

        return files

    def _generate_app(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """メインアプリケーションを生成."""
        return f'''# -*- coding: utf-8 -*-
"""
{workflow.name} - Generated by AgentFlow Studio

{workflow.description}
"""

from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from workflow import workflow_runner


# =============================================================================
# Models
# =============================================================================

class WorkflowInput(BaseModel):
    """ワークフロー入力."""
    data: dict[str, Any] = Field(default_factory=dict)


class WorkflowOutput(BaseModel):
    """ワークフロー出力."""
    status: str
    result: dict[str, Any] | None = None
    error: str | None = None


# =============================================================================
# Application
# =============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """アプリケーションライフサイクル."""
    # Startup
    yield
    # Shutdown


app = FastAPI(
    title="{workflow.name}",
    description="""{workflow.description}""",
    version="{options.version}",
    lifespan=lifespan,
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# Endpoints
# =============================================================================

@app.get("/")
async def root():
    """ルートエンドポイント."""
    return {{"message": "{workflow.name} is running!", "version": "{options.version}"}}


@app.get("/health")
async def health():
    """ヘルスチェック."""
    return {{"status": "healthy"}}


@app.post("/run", response_model=WorkflowOutput)
async def run_workflow(input_data: WorkflowInput):
    """ワークフローを実行."""
    try:
        result = await workflow_runner.run(input_data.data)
        return WorkflowOutput(status="success", result=result)
    except Exception as e:
        return WorkflowOutput(status="error", error=str(e))


@app.post("/stream")
async def stream_workflow(input_data: WorkflowInput):
    """ワークフローをストリーム実行."""
    import json

    async def event_generator():
        try:
            async for event in workflow_runner.run_stream(input_data.data):
                yield f"data: {{json.dumps(event.to_dict())}}\\n\\n"
        except Exception as e:
            yield f"data: {{\\"type\\": \\"error\\", \\"message\\": \\"{e!s}\\"}}\\n\\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


@app.get("/workflow/info")
async def get_workflow_info():
    """ワークフロー情報を取得."""
    return {{
        "id": "{workflow.id}",
        "name": "{workflow.name}",
        "description": "{workflow.description}",
        "nodes": {len(workflow.nodes)},
        "edges": {len(workflow.edges)},
    }}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

    def _generate_workflow(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """ワークフロー定義を生成."""
        # ノードの実行順序を決定
        [node.id for node in workflow.nodes]
        node_types = {node.id: node.agent_type for node in workflow.nodes}

        return f'''# -*- coding: utf-8 -*-
"""
Workflow Definition - {workflow.name}

Generated from AgentFlow Studio workflow.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

from agentflow.core.interfaces import ExecutionEvent, WorkflowDefinition
from agentflow.flow import create_flow


# =============================================================================
# Workflow Configuration
# =============================================================================

WORKFLOW_CONFIG = {{
    "id": "{workflow.id}",
    "name": "{workflow.name}",
    "description": """{workflow.description}""",
    "nodes": {json.dumps([n.id for n in workflow.nodes])},
    "node_types": {json.dumps(node_types)},
}}


# =============================================================================
# Workflow Runner
# =============================================================================

class WorkflowRunner:
    """ワークフロー実行器."""

    def __init__(self) -> None:
        """初期化."""
        self._flow = self._build_flow()

    def _build_flow(self):
        """フローを構築."""
        # TODO: 実際のエージェントをインポートして構築
        flow = create_flow("{workflow.id}")
        # ノード構成:
{self._generate_node_list(workflow)}
        return flow.build()

    async def run(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """ワークフローを実行."""
        # シンプルな実行
        result = await self._flow.run(inputs)
        return result

    async def run_stream(
        self,
        inputs: dict[str, Any],
    ) -> AsyncIterator[ExecutionEvent]:
        """ワークフローをストリーム実行."""
        async for event in self._flow.run_stream(inputs):
            yield ExecutionEvent(
                type=event.get("type", "progress"),
                node_id=event.get("node_id"),
                message=event.get("message", ""),
                progress=event.get("progress"),
                data=event.get("data"),
            )


# グローバルインスタンス
workflow_runner = WorkflowRunner()
'''

    def _generate_config(self, options: CodeGenOptions) -> str:
        """設定ファイルを生成."""
        return f'''# -*- coding: utf-8 -*-
"""Application Configuration."""

import os
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """アプリケーション設定."""

    # Application
    app_name: str = "{options.app_name}"
    app_version: str = "{options.version}"
    debug: bool = False

    # Server
    host: str = "0.0.0.0"
    port: int = 8000

    # LLM
    openai_api_key: str = ""
    anthropic_api_key: str = ""

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


settings = Settings()
'''

    def _generate_requirements(self) -> str:
        """requirements.txt を生成."""
        return """# AgentFlow Generated Application
agentflow>=1.0.0
fastapi>=0.100.0
uvicorn>=0.23.0
pydantic>=2.0.0
pydantic-settings>=2.0.0
httpx>=0.24.0
python-dotenv>=1.0.0
"""

    def _generate_dockerfile(self, options: CodeGenOptions) -> str:
        """Dockerfile を生成."""
        return f"""# {options.app_name} Docker Image
FROM python:3.13-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create non-root user
RUN groupadd -r appuser && useradd -r -g appuser appuser
USER appuser

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""

    def _generate_docker_compose(self, options: CodeGenOptions) -> str:
        """docker-compose.yml を生成."""
        return f"""version: "3.9"

services:
  app:
    build: .
    container_name: {options.app_name}
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
    env_file:
      - .env
    restart: unless-stopped
"""

    def _generate_readme(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """README を生成."""
        return f"""# {workflow.name}

{workflow.description}

## Overview

This application was generated by AgentFlow Studio.

## Setup

```bash
# Install dependencies
pip install -r requirements.txt

# Configure environment
cp .env.example .env
# Edit .env with your settings
```

## Usage

```bash
# Start server
uvicorn app:app --reload

# Or with Docker
docker compose up
```

## API Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | / | Root endpoint |
| GET | /health | Health check |
| POST | /run | Run workflow |
| POST | /stream | Stream workflow execution |
| GET | /workflow/info | Get workflow information |

## Workflow Structure

- Nodes: {len(workflow.nodes)}
- Edges: {len(workflow.edges)}

---

*Generated by AgentFlow Studio v{options.version}*
"""

    def _generate_tests(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """テストコードを生成."""
        return f'''# -*- coding: utf-8 -*-
"""Tests for {workflow.name}."""

import pytest
from fastapi.testclient import TestClient

from app import app


@pytest.fixture
def client():
    """テストクライアント."""
    return TestClient(app)


def test_root(client):
    """ルートエンドポイントのテスト."""
    response = client.get("/")
    assert response.status_code == 200
    assert "message" in response.json()


def test_health(client):
    """ヘルスチェックのテスト."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_workflow_info(client):
    """ワークフロー情報のテスト."""
    response = client.get("/workflow/info")
    assert response.status_code == 200
    data = response.json()
    assert data["id"] == "{workflow.id}"
    assert data["name"] == "{workflow.name}"
'''

    def _generate_env_example(self) -> str:
        """環境変数テンプレートを生成."""
        return """# Application Settings
DEBUG=false

# LLM Providers
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Database (optional)
DATABASE_URL=
"""


__all__ = ["BackendBuilder"]
