"""FullstackBuilder - フルスタックコードビルダー.

React + FastAPI の完全アプリケーションを生成します。
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from agentflow.codegen.builders.backend import BackendBuilder
from agentflow.codegen.builders.base import BaseBuilder
from agentflow.codegen.builders.frontend import FrontendBuilder


if TYPE_CHECKING:
    from agentflow.core.interfaces import CodeGenOptions, WorkflowDefinition


class FullstackBuilder(BaseBuilder):
    """フルスタックコードビルダー.

    Frontend (React) + Backend (FastAPI) の完全アプリケーションを生成します。
    """

    def __init__(self) -> None:
        """初期化."""
        self._backend_builder = BackendBuilder()
        self._frontend_builder = FrontendBuilder()

    async def build(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> dict[str, str]:
        """フルスタックコードをビルド."""
        files: dict[str, str] = {}

        # Backend files (prefix with backend/)
        backend_files = await self._backend_builder.build(workflow, options)
        for path, content in backend_files.items():
            files[f"backend/{path}"] = content

        # Frontend files (prefix with frontend/)
        frontend_files = await self._frontend_builder.build(workflow, options)
        for path, content in frontend_files.items():
            files[f"frontend/{path}"] = content

        # Root files
        files["README.md"] = self._generate_root_readme(workflow, options)
        files["docker-compose.yml"] = self._generate_docker_compose(workflow, options)
        files["Makefile"] = self._generate_makefile(options)
        files[".gitignore"] = self._generate_gitignore()

        return files

    def _generate_root_readme(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """ルート README を生成."""
        return f"""# {workflow.name}

{workflow.description}

## Project Structure

```
{options.app_name}/
├── backend/           # FastAPI backend
│   ├── app.py         # Main application
│   ├── workflow.py    # Workflow definition
│   ├── config.py      # Configuration
│   └── requirements.txt
├── frontend/          # React frontend
│   ├── src/
│   ├── package.json
│   └── vite.config.ts
├── docker-compose.yml # Docker orchestration
├── Makefile           # Build commands
└── README.md          # This file
```

## Quick Start

### Development

```bash
# Start both frontend and backend
make dev

# Or separately:
make dev-backend  # Backend on port 8000
make dev-frontend # Frontend on port 5173
```

### Production

```bash
# Build and run with Docker
docker compose up --build
```

## API Documentation

Once running, visit:
- API Docs: http://localhost:8000/docs
- Frontend: http://localhost:5173

## Configuration

1. Copy environment file:
   ```bash
   cp backend/.env.example backend/.env
   ```

2. Edit `backend/.env` with your settings

## Workflow Info

- **ID**: {workflow.id}
- **Nodes**: {len(workflow.nodes)}
- **Edges**: {len(workflow.edges)}

---

*Generated by AgentFlow Studio v{options.version}*
"""

    def _generate_docker_compose(
        self,
        workflow: WorkflowDefinition,
        options: CodeGenOptions,
    ) -> str:
        """docker-compose.yml を生成."""
        return f"""version: "3.9"

services:
  backend:
    build: ./backend
    container_name: {options.app_name}-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: {options.app_name}-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: {options.app_name}-network
"""

    def _generate_makefile(self, options: CodeGenOptions) -> str:
        """Makefile を生成."""
        return """.PHONY: dev dev-backend dev-frontend build clean test

# Development
dev:
	@echo "Starting development servers..."
	@make -j2 dev-backend dev-frontend

dev-backend:
	cd backend && uvicorn app:app --reload --port 8000

dev-frontend:
	cd frontend && npm run dev

# Build
build:
	docker compose build

build-frontend:
	cd frontend && npm run build

# Run
run:
	docker compose up

run-detached:
	docker compose up -d

# Test
test:
	cd backend && pytest
	cd frontend && npm run test

# Clean
clean:
	docker compose down -v
	rm -rf frontend/node_modules
	rm -rf frontend/dist
	rm -rf backend/__pycache__

# Install
install:
	cd backend && pip install -r requirements.txt
	cd frontend && npm install
"""

    def _generate_gitignore(self) -> str:
        """.gitignore を生成."""
        return """# Python
__pycache__/
*.py[cod]
*$py.class
.Python
.venv/
venv/
.env

# Node
node_modules/
dist/
.npm
*.log

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build
*.egg-info/
build/

# Test
.pytest_cache/
coverage/
.coverage
"""


__all__ = ["FullstackBuilder"]
